<?php

function star_story_menu() {
    $items['star_story'] = array (
        'title' => 'Star Story',
        'description' => t('This is a four-step technique for answering behavioral interview questions. It will help you clearly explain how your past experience applies to particular interview questions.'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('star_story_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['star_story_success_page'] = array(
        'title' => 'Success',
        'page callback' => 'star_story_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function star_story_form() {
    $form['situation'] = array (
        '#title' => 'Situation',
        '#type' => 'textfield',
        '#description' => t('Describe the task you were asked to do.'),
        '#element_validate' => array(),
        '#required' => TRUE,
    );
    $form['task'] = array (
        '#title' => 'Task',
        '#type' => 'textfield',
        '#description' => t('Describe the tasks, jobs, or problems you were assigned to complete.'),
        '#element_validate' => array(),
        '#required' => TRUE,
    );
    $form['action'] = array (
        '#title' => 'Action',
        '#type' => 'textarea',
        '#description' => t('Describe the actions you took. Be sure to use "I" statements.'),
        '#element_validate' => array(),
        '#required' => TRUE,
    );
    $form['result'] = array (
        '#title' => 'Result',
        '#type' => 'textarea',
        '#description' => t('Describe the results of the actions you took. Be sure to include numbers if applicable.'),
        '#element_validate' => array(),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt',
    );
    return $form;
}
