<?php

function shift_cipher_menu() {
    $items[shift_cipher] = array (
        'title' => 'Shift Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array(shift_cipher_form),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items[shift_cipher_success_page] = array(
        'title' => 'Success',
        'page callback' => 'shift_cipher_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function shift_cipher_form() {
    $form['shift_value'] = array (
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => t('Please enter the number of letters you would like to shift.'),
        '#element_validate' => array('element_validate_integer_positive', 'element_validate_range'),
        '#required' => TRUE,
    );
    $form['shift_direction'] = array (
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => t('Please enter the direction to shifr, either left or right.'),
        '#element_validate' => array('element_validate_direction'),
        '#required' => TRUE,
    );
    $form['shift_phrase'] = array (
        '#title' => 'Shift Phrase',
        '#type' => 'textfield',
        '#description' => t('Please enter the phrase you would like to encrypt.'),
        '#element_validate' => array('element_validate_characters'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt',
    );
    return $form;
}

function element_validate_range($element) {
    $value = $element['#value'];
    if ($value > 25) {
        form_error($element, t('Please enter a value between 1 and 25.'));
    }
}

function element_validate_direction($element) {
    $direction = strtolower($element['#value']);
    if ($direction !== 'right' && $direction !== 'left') {
        form_error($element, t('Please enter right, or left.'));
    }
}

function element_validate_characters($element) {
    $phrase = $element['#value'];
    if (preg_match('/[\^£$%&*()}{@#~?><>|=_+¬-]/', $phrase)) {
        form_error($element, t('Please avoid using any special characters.'));
    }
}

function shift_cipher_form_submit($form, &$form_state) {
    $alphabet_key = array('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z');

    $value = $form_state['values']['shift_value'];
    $direction = $form_state['values']['shift_direction'];
    $phrase = str_split($form_state['values']['shift_phrase']);
    $encrypted_array = array();

    foreach ($phrase as $letter) {
      if (preg_match('/[!?.,":;\'\-\s*]/', $letter) === 1) {
          array_push($encrypted_array, $letter);
      } else {
          for ($i = 0; $i < count($alphabet_key); $i++) {
              if ($alphabet_key[$i] === $letter || strtoupper($alphabet_key[$i]) === $letter) {
                  if ($direction === 'right') {
                      $shifted_value = $i + $value;
                  } else {
                      $shifted_value = $i - $value;
                  }
                  if ($shifted_value < 0 || $shifted_value > 25) {
                      $shifted_value = abs($shifted_value % 26);
                  }
                  if ($letter === strtoupper($alphabet_key[$i])) {
                      array_push($encrypted_array, strtoupper($alphabet_key[$shifted_value]));
                  } else {
                      array_push($encrypted_array, $alphabet_key[$shifted_value]);
                  }
              }
          }
      }
    }
    $encrypted_text = implode($encrypted_array);
    $_SESSION['encryption'] = $encrypted_text;

    $form_state['redirect'] = 'shift_cipher_success_page';
}

function shift_cipher_success() {
    $cipher = $_SESSION['encryption'];
    return 'Here is your encrypted message: ' . $cipher;
}
